version: '3'

services:
  mysql:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3307:3306"

  myapp:
    image: docker_java_doc_compose_myapp:latest
    environment:
      - DISPLAY=:0
    depends_on:
      - mysql
