version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
    volumes:
      - ./frontend:/app/frontend
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  frontend-volume:
